<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/feather.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/owl.carousel.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/magnific-popup.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/lc_lightbox.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/bootstrap-select.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/select.bootstrap5.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/dropzone.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/scrollbar.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/datepicker.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/flaticon.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/swiper-bundle.min.css">
<link rel="stylesheet" type="text/css" href="{{ asset('front') }}/css/style.css">
